Import('sys', 'env', 'hasCollada', 'stubs', 'winstubs')

# Create an environment with Xerces and OpenGL
mainEnv = env.Clone()
if 'XERCESINCLUDE' in mainEnv:
        mainEnv.Prepend(CPPPATH=mainEnv['XERCESINCLUDE'])
if 'XERCESLIBDIR' in mainEnv:
        mainEnv.Prepend(LIBPATH=mainEnv['XERCESLIBDIR'])
if 'XERCESLIB' in mainEnv:
        mainEnv.Prepend(LIBS=mainEnv['XERCESLIB'])
if 'GLLIB' in mainEnv:
        mainEnv.Prepend(LIBS=mainEnv['GLLIB'])
if 'GLLIBDIR' in mainEnv:
        mainEnv.Prepend(LIBPATH=mainEnv['GLLIBDIR'])
if 'GLFLAGS' in mainEnv:
        mainEnv.Prepend(CXXFLAGS=mainEnv['GLFLAGS'])
if 'GLINCLUDE' in mainEnv:
        mainEnv.Prepend(CPPPATH=mainEnv['GLINCLUDE'])

mainEnv.Program('mtsutil', stubs + winstubs + ['mtsutil.cpp'])

# Build the command-line+GUI interface
mainEnv.Program('mtssrv',  winstubs + ['mtssrv.cpp'])
mainEnv.Program('mitsuba', winstubs + ['mitsuba.cpp'])

Return('mainEnv')
