Import('env', 'plugins')

mb_env = env.Clone()
mb_env['CPPPATH'].append('E:/Code/3rdlibs/glm/include')
mb_env['LIBS'].append('glm')
mb_env['LIBPATH'].append('E:/Code/3rdlibs/glm/lib')

plugins += mb_env.SharedLibrary('mbsmithconductor', ['MicrosurfaceScattering.cpp', 'roughconductor.cpp'])
plugins += mb_env.SharedLibrary('mbsmithdielectric', ['MicrosurfaceScattering.cpp', 'roughdielectric.cpp'])
plugins += mb_env.SharedLibrary('mbsmithdiffuse', ['MicrosurfaceScattering.cpp', 'roughdiffuse.cpp'])